import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "@/Components/Layouts/Navber";
import Footer from "@/Components/Layouts/Footer";
import AuthProvider from "@/Provider/AuthProvider";
import { ToastContainer } from "react-toastify";
import QueryProvider from "@/Query/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <QueryProvider>
        
      <AuthProvider>
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-200`}
      > 
         
        <header>
          <Navber></Navber>
         </header>
        
        {children}

        <footer>
          <Footer></Footer>
        </footer>
      </body>
      </AuthProvider>
   
   </QueryProvider>
    </html>
  );
}
