import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardNavbar from "@/Components/Layouts/DashboardNavber";
import AuthProvider from "@/Provider/AuthProvider";
import QueryProvider from "@/Query/QueryProvider";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "ProjectPulse",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        
        <html lang="en" suppressHydrationWarning>
          
            <QueryProvider>
                
                <AuthProvider>
                
                    <body
                        className={`${geistSans.variable} antialiased flex flex-col lg:grid gap-4 bg-base-200 grid-cols-12`}
                        suppressHydrationWarning
                    >
                        
                        <header className="col-span-3">
                            <DashboardNavbar></DashboardNavbar>
                 
                        </header>

                      
                        <main className="col-span-9">{children}</main>

                    </body>
                </AuthProvider>
            </QueryProvider>
        </html>
    );
}