import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardNavbar from "@/Components/Layouts/DashboardNavber";
import AuthProvider from "@/Provider/AuthProvider";
import QueryProvider from "@/Query/QueryProvider";
import PrivateRoute from "@/Provider/PrivateRoute";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "ProjectPulse",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        
        <html lang="en" suppressHydrationWarning className="dark">
          
                
                
                    <body
                        className={`${geistSans.variable} antialiased lg:grid gap-4 grid-cols-12 dark:bg-slate-950 dark:text-slate-100`}
                       
                        >
                        <AuthProvider>
                        <QueryProvider>
                    <PrivateRoute>
                            <header className="col-span-3 bg-slate-900 dark:bg-slate-900 border-r sticky top-0 z-50 border-slate-700 dark:border-slate-700 shadow-sm lg:shadow-none">
                            <DashboardNavbar></DashboardNavbar>
                 
                        </header>

                        <main className="col-span-9 dark:bg-slate-950">{children}</main>

                    </PrivateRoute>
            </QueryProvider>
                </AuthProvider>
                    
                    </body>
        </html>
    );
}